### ISSUE TITLE
Use text from Clipboard when expanding text

### ISSUE THREAD

**Issue by sensen** [sensen/typing-hero#11]

**Comment by Rainer-Lang** [comment]
What is a "special snippet" or could you give a bit more details about this feature?

**Comment by sensen** [comment]
The idea for this feature is when you typed a predefined keyword (maybe customizable as well), such as `zpaste`, it will automatically paste the content in your Clipboard.

I'm still unsure how this "special snippet" will appear in the app. 😄 

@Rainer-Lang

**Comment by sensen** [comment]
Published!

But this is not so "special" just yet. It's just another placeholder like Cursor, Date & Time. @Rainer-Lang
