### ISSUE TITLE
Search in snippet list screen

### ISSUE THREAD

**Issue by sensen** [sensen/typing-hero#13]
Search in `keyword` and `text` field.

**Comment by Rainer-Lang** [comment]
Search in keywords and/or replacements?

**Comment by sensen** [comment]
> Search in keywords and/or replacements?

Yes.

**Comment by Rainer-Lang** [comment]
Maybe this could help: https://github.com/mikepenz/FastAdapter

**Comment by KnorpelSenf** [comment]
This enhancement is already provided, isn't it?

**Comment by sensen** [comment]
You're right! Closing this one.
