### ISSUE TITLE
When replacing keyword with text, adjust the text's first character's case to follow key's first character's case

### ISSUE THREAD

**Issue by sensen** [sensen/typing-hero#20]
```
Snippet {
  keyword: "ty",
  text: "thank you!"
}
```

`ty` -> `thank you!`
`Ty` -> `Thank you!`
`TY` -> `THANK YOU!`

**Comment by Rainer-Lang** [comment]
Please make this adjustable.

**Comment by sensen** [comment]
I'm thinking of the same, too, per snippet. What do you think?

**Comment by Rainer-Lang** [comment]
> I'm thinking of the same, too, per snippet. What do you think?

per snippet it's fine :-)

**Comment by sensen** [comment]
@Rainer-Lang Mate, I'm thinking of making this not configurable. Can you please argue me out of this thinking?

**Comment by sensen** [comment]
Published.
