### ISSUE TITLE
Translation: German

### ISSUE THREAD

**Issue by sensen** [sensen/typing-hero#22]

**Comment by Rainer-Lang** [comment]
Please contact me. I would like to help.

**Comment by sensen** [comment]
> Please contact me. I would like to help.

Will you be okay if I sent you an XML file of the English language, and ask your help to translate it to German manually? @Rainer-Lang

**Comment by Rainer-Lang** [comment]
Of course.

**Comment by sensen** [comment]
I've sent it to your email.

**Comment by Rainer-Lang** [comment]
translation finished. Maybe someone could doublecheck.

**Comment by sensen** [comment]
Published to Google Play.
