### ISSUE TITLE
Translation: Spanish

### ISSUE THREAD

**Issue by sensen** [sensen/typing-hero#23]

**Comment by ghost** [comment]
Could I do that?

**Comment by sensen** [comment]
> Could I do that?

Of course you can, good Samaritan! Since I'm not using any translation system just yet, do you mind if I send you the XML files of the English language, and let's start from there? If you're okay, write me an email to typingheroapp@gmail.com, and I'll send you the file.

**Comment by ghost** [comment]
Good! I'm learning how to use Github, but the native language is there and fully working :smiley:

**Comment by sensen** [comment]
Published to Google Play.
