### ISSUE TITLE
Categories for snippets

### ISSUE THREAD

**Issue by illumi241** [sensen/typing-hero#25]
The list of snippets is growing fast when using the app for a while.

To better organize snippets, it would be great to have categories / groups or some kind of folders.

**Comment by sensen** [comment]
Basically #3 allows you to sort of group text in the same contex to your liking. 

For example, you could have a snippet with keyword `zemail`, and assign all emails you own there.

Or, you could have a snippet with keyword `zoffice`, and assign all information related to your office there, such as address, phone, direction to your office building, etc.

Any thoughts @illumi241?

**Comment by illumi241** [comment]
@sensen I mean grouping for the app to visually organize the snippets better, so you could have a group "Greetings" where you store all your greetings, one "Addresses" where you store addresses and so on.
They still would have their own shortcut but they would be visually grouped in the app, maybe like a tree  or folder structure.

But the features could be combined of course, so that you can assign a shortcut to get all contents of the group in a list.

**Comment by Rainer-Lang** [comment]
Grouping (folders) would be really great. :+1:

**Comment by sensen** [comment]
Published! @illumi241 @Rainer-Lang
