### ISSUE TITLE
Share all snippets in a human readable format to other apps

### ISSUE THREAD

**Issue by Hoomum** [sensen/typing-hero#27]
I am inputting some new codes. There is a function that would be great for people with long lists: ability to share or print list of codes. That way you can refer to them until you learn them.

By share I mean the Google share menu that allows you to share to other apps and share to a network or cloud printer.

**Comment by sensen** [comment]
Sharing to other apps should be quite straightforward. I guess the output format is essential. What do you think?

```
Keyword: zpn
Text: +44 7700 900796

Keyword: zll
Text: +44 1632 960448
```

I've never done network/cloud printer, so I don't know much about this.

**Comment by Hoomum** [comment]
I think yes keyword and then the text is perfect.

As long as there is a share to menu then that should be alright. I think print is a default option. In my apps I have a few printer apps anyway. They are Printershare, Epson iPrint and HPSmart so I can print by sharing to one of these apps.

**Comment by sensen** [comment]
Great!

**Comment by sensen** [comment]
Published to Google Play.
