### ISSUE TITLE
Show list of partially matching keyword when typing

### ISSUE THREAD

**Issue by sensen** [sensen/typing-hero#7]
As user types on other apps, if Typing Hero observes the (possible) keyword typed is more than 2 characters, show list of snippets which has (partially) matching keyword in a floating view that can be dragged around.

Tapping on a snippet in the list will replaced the (possible) keyword with text associated with the snippet, and then dismiss the floating view.

The list of snippets will be dismissed if user continue to type, and there were no snippets with such keyword.

**Comment by Hoomum** [comment]
This would be a great feature. Especially if there is a very long list of commands.

**Comment by sensen** [comment]
I'm thinking to show the list after typing more than 2 letter. Does it make sense to you? @Hoomum

**Comment by Rainer-Lang** [comment]
Would be good for me.

**Comment by sensen** [comment]
Thank you for confirming @Rainer-Lang

**Comment by sensen** [comment]
I wonder if the threshold of more than 2 characters should be configurable in Settings.

**Comment by sangampandasp9** [comment]
I think it will be better to import the snippets to gdrive and also sync them automatically for even better implementation!! @sensen

**Comment by sangampanda** [comment]
That would be a great implementation for this!! 👍🏼

**Comment by sensen** [comment]
Published to Google Play.
