### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by KnorpelSenf** [sensen/typing-hero#76]
A rather sophisticated approach to advanced text editing would be _templates_ which could for instance work as follows.

In the snippet editor view, it is possible to insert special tags into the snippet text. They have a custom defined text. An example snippet (key: `zpostponed`) would look like this:
>
> Hi `<user>`,
> I'm sorry to tell you that we currently don't have the capacity to do this. However, your idea is in the backlog and you can expect to hear from me again `<when>`.
> Best,
> Your Friendly Support Team
>
Typing `zpostponed` would then insert the above text. The part `<user>` is selected. The user can then type a name and press enter (that is, insert a newline). This key (character rather) could be made configurable in order to support newline characters in template slots. Upon pressing enter, the next slot is selected. In this case it is `<when>`.

Assuming the user has another snippet in addition to the above (key: `zmon`, text: `by Monday next week`), she can write `zmon` while `<time>` is still selected. This would therefore expand the snippet while editing a template slot, all while not moving the focus to the (hypothetical in our case) next slot. Once the enter key is pressed, the next slot is selected. If all slots are filled, the cursor jumps to the final position of the aforementioned snippet.

There are still quite a few open questions. It needs to be determined what happens if:

1) The user wants to undo the action.
1) The user wants to undo an action further down recursion (snippet expansion in slot in a slot in a slot?) This gets arbitrarily complex, a full tree of possibilities if not constrained in a smart way
1) The user wants to have arbitrary characters in slots, does this require a special keyword for slot-switching?
1) How are physical keyboards handled? Pressing tab on one of those would be intuitive to switch slots, but can this be detected?

A feature like this is most likely highly complex to implement because of the necessity of a full flow of actions. It needs to be worked out how to specify this behaviour in an unambiguous way.

Most importantly, templates needs to work so intuitively that (almost) no tutorials are required for the end users.

**Comment by sensen** [comment]
This is valid use case that I encountered quite often, such as when replying email from users, or responding to Google Play Store reviews.

The solution you propose is possible, though as you said, it will be quite involved in terms of effort.

When I encounter this issue, I think of few alternatives.

1. Introduce a special tag asking for user input. In your case, `<user>`, `<when>`, `<time>` can be replaced with `<input>`. Upon seeing this tag, it could either select the text _after_ expansion, or showing a dialog with a list of input (as many as found `<input>` tags), so user can fill it in _before_ expansion.

1. Introduce `<cursor>` tag #53, which basically place cursor at its designated position, with an overlay showing navigation button to navigate across all found `<cursor>` tags. User can move around and type whatever they want, including any keyword that will be expanded.

1. (This is already in my internal backlog) Introduce a special tag `$keyword$` which can be used in a snippet's defined text. Say you have a snippet with keyword `next3days` which will expand into the date of three days from now (assuming the relative date/time feature is already available).
>
> However, your idea is in the backlog and you can expect to hear from me again `$next3days$`.
>

Regarding the open questions:
1. This really depends on the implementation. I prefer to have a single text expansion, with all kind of transformation happening behind. By transformation, I mean the date/time, user input, keyword. With the exception of cursor placement, of course.

1. This will get very complex as you said, and I'd rather stray from this. One text expansion, and one undo level.

1. I'm not sure if I understand you correctly; by slot, do you mean something like `<user>` or `<when>`? If so, I think `<input>` kind of answer this.

1. I'm sure it's possible, but I don't have much experience with that. Physical keyboard support has never been tested at all.

**Comment by KnorpelSenf** [comment]
I see I was not being clear about the `<input>` tags. I was thinking that they could be inserted with a custom word instead of input, so that I have some hint about what I was expecting myself to enter here. And yes, I called them slots in lack of a better name.

However, I've mostly been describing a feature given unlimited time an resources to make clear what I was aiming at. It's clear that this needs to be cut down in some ways to be realistic. Not having those words would be one example of this, limiting the revision depth to 1 is another one.

**Comment by sensen** [comment]
> I see I was not being clear about the <input> tags. I was thinking that they could be inserted with a custom word instead of input, so that I have some hint about what I was expecting myself to enter here. 

Got it. I think maybe instead of tag, then a delimiter can be used for this purpose. `##user##` will show an input with the text hint "user", and so on.

> And yes, I called them slots in lack of a better name.

Got it.

> However, I've mostly been describing a feature given unlimited time an resources to make clear what I was aiming at. It's clear that this needs to be cut down in some ways to be realistic. Not having those words would be one example of this, limiting the revision depth to 1 is another one.

Understood. I wish there are more like this.

**Comment by Nik401** [comment]
I'm agree with you sar...
Please add this feature.... 💐
Thank you so much... 🎉

**Comment by sensen** [comment]
I pushed this one out just now. Would love to get feedback on what could be improved.

**Comment by KnorpelSenf** [comment]
Will look into it in the coming days! Do you prefer feedback here or on Telegram?

**Comment by sensen** [comment]
Whichever you're comfortable with. Hope you're doing well. Stay safe!
